Repository nucosen/broadcast, pull requests merged in 2023-10, with the labels that each got.

#100 環境変数MAINTENACE_MOVIE_IDとENDING_MOVIE_IDの追加
  .github/workflows/python-app.yml
  src/nucosen/nucosen.py
Labels: p3:新機能

#101 調整中・放送終了動画関連の環境設定を追加
  .gitignore
  docs/config.md
  docs/errorMessage.md
  docs/index.md
  docs/requirements.md
  docs/troubleShooting.md
  src/nucosen/nucosen.py
Labels: p3:新機能, p3:リファクタリング

#106 軽微な修正
  .gitignore
  src/nucosen/live.py
Labels: p3:リファクタリング
